[package]
name = "Bob-the-fire-extinguisher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
robotics_lib = { git = "https://github.com/Advanced-Programming-2023/Robotic-Lib", branch = "master" }